version: "3.8"
services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - stored_docs:/app/uploads
    env_file: ./server/.env
    links:
      - database # link this service to the database service
  birthday_cron:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./micro_services/birthday_cron
    depends_on:
      - 'nginx'
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - 'api'
  database:
    restart: always
    image: mongo:4.0.4 # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    volumes:
      - mongodata:/data/db
      - ./db/convey_feed:/dump/convey_feed
volumes:
  mongodata:
  stored_docs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/server/uploads'
