version: "3.8"
services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server/uploads:/server/uploads
    env_file: ./server/.env
    links:
      - database # link this service to the database service
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - 'api'
  database:
    restart: always
    image: mongo:4.0.4 # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    volumes:
      - mongodata:/data/db
      - ./db/convey_feed:/dump/convey_feed
volumes:
  mongodata:
