version: "3.8"
services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
    env_file: ./server/.env
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'

